name: C/C++ CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: cmake-configuring
      run: cmake .
    - name: cmake-build
      run: cmake --build .
