name: C/C++ CI
# Workflow file for windows
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  Windows:
    name: build-windows
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Running cmake (windows)
        run: |
          cd ${{ github.workspace }}
          mkdir build
          cd build
          cmake ../
      - name: Building the project
        run: |
          cd ${{ github.workspace }}
          cd build
          cmake --build .